# Generated by Django 5.2.17 on 2026-09-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_denied_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token_version',
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
    ]
