# Generated by Django 5.2.17 on 2026-09-03 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom interne')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('printer_type', models.CharField(default='thermal', max_length=50, verbose_name='Type d’imprimante')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Constructeur')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Modèle')),
                ('connection_mode', models.CharField(choices=[('bluetooth', 'Bluetooth'), ('usb', 'USB'), ('network', 'Réseau TCP/IP'), ('windows', 'Imprimante système Windows'), ('android', 'Android Print Service'), ('other', 'Autre')], max_length=20, verbose_name='Mode de connexion')),
                ('local_identifier', models.CharField(blank=True, help_text='Préférence non secrète uniquement. La découverte Bluetooth reste locale au terminal.', max_length=255, verbose_name='Identifiant local facultatif')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('network_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='Port réseau')),
                ('paper_width', models.PositiveSmallIntegerField(choices=[(58, '58 mm'), (80, '80 mm')], default=80, verbose_name='Largeur papier')),
                ('protocol', models.CharField(choices=[('generic_escpos', 'Generic ESC/POS'), ('epson_escpos', 'Epson compatible ESC/POS'), ('xprinter', 'XPrinter'), ('sunmi', 'Sunmi'), ('star', 'Star'), ('posiflex', 'Posiflex'), ('gp', 'GP'), ('custom', 'Autre protocole')], default='generic_escpos', max_length=30, verbose_name='Protocole')),
                ('characters_per_line', models.PositiveSmallIntegerField(default=48, verbose_name='Caractères par ligne')),
                ('encoding', models.CharField(default='cp858', max_length=50, verbose_name='Encodage')),
                ('auto_print', models.BooleanField(default=False, verbose_name='Impression automatique')),
                ('is_default', models.BooleanField(default=False, verbose_name='Imprimante par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'permissions': (('test_printerprofile', 'Peut générer un test d’impression'),),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='one_default_printer'), models.CheckConstraint(condition=models.Q(('paper_width__in', (58, 80))), name='printer_paper_width_supported'), models.CheckConstraint(condition=models.Q(('characters_per_line__gte', 16)), name='printer_chars_per_line_gte_16')],
            },
        ),
        migrations.CreateModel(
            name='UserPrinterPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_preferences', to='printing.printerprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printer_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('document_type', models.CharField(choices=[('ticket_58', 'Ticket 58 mm'), ('ticket_80', 'Ticket 80 mm'), ('invoice_a4', 'Facture A4'), ('purchase_order', 'Bon d’achat'), ('delivery_note', 'Bon de livraison'), ('product_label', 'Étiquette produit')], max_length=30, verbose_name='Type de document')),
                ('paper_width', models.PositiveSmallIntegerField(blank=True, choices=[(58, '58 mm'), (80, '80 mm')], null=True, verbose_name='Largeur papier')),
                ('copies', models.PositiveSmallIntegerField(default=1, verbose_name='Nombre de copies')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe'), ('en', 'Anglais'), ('bilingual', 'Bilingue français/arabe')], default='bilingual', max_length=15, verbose_name='Langue')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_profiles', to='printing.printerprofile')),
            ],
            options={
                'ordering': ('document_type', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('copies__gte', 1)), name='print_profile_copies_gte_1')],
            },
        ),
    ]
