# Generated by Django 5.2.17 on 2026-09-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_seed_profiles_and_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerprofile',
            name='bluetooth_address',
            field=models.CharField(blank=True, max_length=17, verbose_name='Adresse Bluetooth'),
        ),
        migrations.AddField(
            model_name='printerprofile',
            name='bluetooth_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom Bluetooth'),
        ),
    ]
