# Generated by Django 5.2.17 on 2026-09-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_printerprofile_bluetooth_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerprofile',
            name='print_invoices',
            field=models.BooleanField(default=True, verbose_name='Imprimer les factures'),
        ),
        migrations.AddField(
            model_name='printerprofile',
            name='print_receipts',
            field=models.BooleanField(default=True, verbose_name='Imprimer les tickets'),
        ),
        migrations.AlterField(
            model_name='printerprofile',
            name='printer_type',
            field=models.CharField(choices=[('thermal', 'Thermique'), ('inkjet', 'Jet d’encre'), ('laser', 'Laser'), ('other', 'Autre type')], default='thermal', max_length=50, verbose_name='Type d’imprimante'),
        ),
    ]
