# Generated by Django 5.2.15 on 2026-06-29 10:28

import apps.core.security
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=16, verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='path',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Code HTTP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.security.company_logo_upload_to, validators=[apps.core.security.validate_image_upload], verbose_name='Logo entreprise'),
        ),
    ]
