# Generated by Django 5.2.17 on 2026-10-03 20:01

from django.db import migrations, models


def configure_company_legal_identifiers(apps, schema_editor):
    CompanySettings = apps.get_model('core', 'CompanySettings')
    values = {
        'nis': '002610010000282',
        'tax_number': '002610028552077',
        'rc_number': '10/00-0285520 B26',
        'article_number': '10018109008',
    }
    company = CompanySettings.objects.order_by('pk').first()
    if company is None:
        CompanySettings.objects.create(**values)
        return
    for field, value in values.items():
        setattr(company, field, value)
    company.save(update_fields=tuple(values))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog_audit_action_ip_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='article_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Article d’imposition (AI)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='nis',
            field=models.CharField(blank=True, max_length=100, verbose_name='NIS'),
        ),
        migrations.RunPython(
            configure_company_legal_identifiers,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
