from django.urls import path
from .views import (
    product_list,
    product_create,
    product_update,
    product_delete,
    product_import,
    product_export,
    client_list,
    client_create,
    client_update,
    client_delete,
    supplier_list,
    supplier_create,
    supplier_update,
    supplier_delete,
    stock_movement_list,
    stock_movement_create,
    stock_movement_delete,
    product_detail,
    product_qr_download,
)

urlpatterns = [
    path('products/', product_list, name='product_list'),
    path('products/new/', product_create, name='product_create'),
    path('products/<int:pk>/edit/', product_update, name='product_update'),
    path('products/<int:pk>/delete/', product_delete, name='product_delete'),
    path('products/<int:pk>/', product_detail, name='product_detail'),
    path('products/<int:pk>/download_qr/', product_qr_download, name='product_qr_download'),
    path('products/import/', product_import, name='product_import'),
    path('products/export/', product_export, name='product_export'),
    path('clients/', client_list, name='client_list'),
    path('clients/new/', client_create, name='client_create'),
    path('clients/<int:pk>/edit/', client_update, name='client_update'),
    path('clients/<int:pk>/delete/', client_delete, name='client_delete'),
    path('suppliers/', supplier_list, name='supplier_list'),
    path('suppliers/new/', supplier_create, name='supplier_create'),
    path('suppliers/<int:pk>/edit/', supplier_update, name='supplier_update'),
    path('suppliers/<int:pk>/delete/', supplier_delete, name='supplier_delete'),
    path('stock-movements/', stock_movement_list, name='stock_movement_list'),
    path('stock-movements/new/', stock_movement_create, name='stock_movement_create'),
    path('stock-movements/<int:pk>/delete/', stock_movement_delete, name='stock_movement_delete'),
]
