# Generated by Django 5.2.15 on 2026-06-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='Référence'),
        ),
    ]
