# Generated by Django 5.2.15 on 2026-06-28 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_barcode_image_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Conditionnement')),
                ('unit_quantity', models.PositiveIntegerField(default=1, verbose_name="Quantité d'unités de base")),
                ('default_sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de vente par défaut')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code-barres conditionnement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Conditionnement produit',
                'verbose_name_plural': 'Conditionnements produit',
                'ordering': ['product__name', 'unit_quantity', 'name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'name'), name='unique_packaging_name_per_product'), models.CheckConstraint(condition=models.Q(('unit_quantity__gte', 1)), name='packaging_unit_quantity_gte_1')],
            },
        ),
    ]
