# Generated by Django 5.2.15 on 2026-06-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_remove_saleline_packaging'),
        ('inventory', '0005_seed_base_product_packagings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPackaging',
        ),
    ]
