# Generated by Django 5.2.15 on 2026-06-29 10:28

import apps.core.security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_delete_productpackaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.security.product_photo_upload_to, validators=[apps.core.security.validate_image_upload], verbose_name='Photo'),
        ),
    ]
