# Generated by Django 5.2.17 on 2026-08-16 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_reconcile_stock_baseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du conditionnement')),
                ('conversion_factor', models.PositiveIntegerField(help_text="Nombre d'unités de base contenues dans ce conditionnement.", verbose_name='Facteur de conversion')),
                ('default_sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de vente par défaut')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code-barres')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='inventory.product')),
            ],
            options={
                'ordering': ('product__name', 'conversion_factor', 'name'),
                'constraints': [models.UniqueConstraint(fields=('product', 'name'), name='uniq_packaging_name_per_product'), models.CheckConstraint(condition=models.Q(('conversion_factor__gte', 1)), name='packaging_factor_gte_1'), models.CheckConstraint(condition=models.Q(('default_sale_price__gte', 0)), name='packaging_price_gte_0')],
            },
        ),
    ]
