# Generated by Django 5.2.17 on 2026-09-03 15:44

from django.db import migrations, models


def copy_existing_retail_prices(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    Product.objects.all().update(
        super_wholesale_price=models.F('sale_price'),
        wholesale_price=models.F('sale_price'),
        retail_price=models.F('sale_price'),
    )


def grant_pricing_permission(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    content_type, _created = ContentType.objects.get_or_create(
        app_label='inventory', model='product'
    )
    permission, _created = Permission.objects.get_or_create(
        content_type=content_type,
        codename='view_product_pricing',
        defaults={'name': 'Peut voir les trois tarifs produit'},
    )
    for group in Group.objects.filter(name__in=['Administrateur', 'Gestionnaire']):
        group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_denied_permissions'),
        ('inventory', '0012_productpackaging'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('view_product_pricing', 'Peut voir les trois tarifs produit')], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AddField(
            model_name='client',
            name='customer_type',
            field=models.CharField(choices=[('SUPER_WHOLESALE', 'Super Gros'), ('WHOLESALE', 'Gros'), ('RETAIL', 'Détail')], default='RETAIL', max_length=20, verbose_name='Type de client'),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix Détail'),
        ),
        migrations.AddField(
            model_name='product',
            name='super_wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix Super Gros'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix Gros'),
        ),
        migrations.RunPython(copy_existing_retail_prices, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(
                condition=models.Q(super_wholesale_price__gte=models.F('purchase_price')),
                name='product_super_price_gte_cost',
            ),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(
                condition=models.Q(wholesale_price__gte=models.F('purchase_price')),
                name='product_wholesale_price_gte_cost',
            ),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(
                condition=models.Q(retail_price__gte=models.F('purchase_price')),
                name='product_retail_price_gte_cost',
            ),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(super_wholesale_price__lte=models.F('wholesale_price'))
                    & models.Q(wholesale_price__lte=models.F('retail_price'))
                ),
                name='product_price_tiers_ordered',
            ),
        ),
        migrations.RunPython(grant_pricing_permission, migrations.RunPython.noop),
    ]
