# Generated by Django 5.2.17 on 2026-09-13 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_client_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingOrderSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='source_type',
            field=models.CharField(choices=[('legacy', 'Historique antérieur'), ('manual', 'Saisie manuelle'), ('product', 'Fiche produit'), ('import', 'Import produits'), ('purchase', 'Achat'), ('sale', 'Vente'), ('loading', 'Chargement opérateur'), ('reversal', 'Annulation')], default='manual', editable=False, max_length=16, verbose_name='Origine'),
        ),
        migrations.CreateModel(
            name='LoadingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Numéro')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validé'), ('in_progress', 'En cours'), ('closed', 'Clôturé'), ('cancelled', 'Annulé')], db_index=True, default='draft', max_length=16, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_loading_orders', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loading_orders', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'permissions': [('validate_loadingorder', 'Peut valider un bon de chargement'), ('close_loadingorder', 'Peut clôturer un bon de chargement'), ('view_all_loadingorders', 'Peut voir tous les chargements')],
            },
        ),
        migrations.CreateModel(
            name='LoadingOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité chargée')),
                ('returned_quantity', models.PositiveIntegerField(default=0, editable=False, verbose_name='Quantité retournée')),
                ('loading_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.loadingorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loading_lines', to='inventory.product')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='OperatorStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_stocks', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operator_stocks', to='inventory.product')),
            ],
            options={
                'ordering': ('product__name', 'product_id'),
            },
        ),
        migrations.CreateModel(
            name='OperatorStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('load', 'Chargement'), ('sale', 'Vente'), ('return', 'Retour dépôt'), ('reversal', 'Contrepassation')], max_length=16)),
                ('quantity', models.PositiveIntegerField()),
                ('applied_delta', models.IntegerField(editable=False)),
                ('balance_before', models.PositiveIntegerField(editable=False)),
                ('balance_after', models.PositiveIntegerField(editable=False)),
                ('source_reference', models.CharField(blank=True, editable=False, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loading_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.loadingorder')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operator_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operator_stock_movements', to='inventory.product')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='loadingorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('validated', 'in_progress'))), fields=('operator',), name='uniq_active_loading_per_operator'),
        ),
        migrations.AddConstraint(
            model_name='loadingorderline',
            constraint=models.UniqueConstraint(fields=('loading_order', 'product'), name='uniq_product_per_loading'),
        ),
        migrations.AddConstraint(
            model_name='loadingorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='loading_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='loadingorderline',
            constraint=models.CheckConstraint(condition=models.Q(('returned_quantity__gte', 0)), name='loading_returned_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='operatorstock',
            constraint=models.UniqueConstraint(fields=('operator', 'product'), name='uniq_operator_product_stock'),
        ),
        migrations.AddConstraint(
            model_name='operatorstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='operator_stock_non_negative'),
        ),
        migrations.AddIndex(
            model_name='operatorstockmovement',
            index=models.Index(fields=['operator', 'product', '-created_at'], name='opstock_operator_prod_idx'),
        ),
    ]
