# Generated by Django 5.2.17 on 2026-10-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_loadingordersequence_alter_stockmovement_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='article_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro d’article'),
        ),
        migrations.AddField(
            model_name='client',
            name='nis',
            field=models.CharField(blank=True, max_length=100, verbose_name='NIS'),
        ),
        migrations.AddField(
            model_name='client',
            name='trade_register_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro de registre de commerce'),
        ),
    ]
