# Generated by Django 5.2.15 on 2026-06-28 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('inventory', '0005_seed_base_product_packagings'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productpackaging'),
        ),
    ]
