# Generated by Django 5.2.15 on 2026-06-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_seed_invoice_sequences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleline',
            name='packaging',
        ),
    ]
