# Generated by Django 5.2.15 on 2026-08-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_remove_saleline_packaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Séquence ticket',
                'verbose_name_plural': 'Séquences tickets',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('cheque', 'Chèque'), ('transfer', 'Virement')], default='cash', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='sale',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Numéro ticket'),
        ),
    ]
