# Generated by Django 5.2.17 on 2026-08-15 13:14

import django.db.models.deletion
from uuid import uuid4

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q, Sum


def audit_payments_and_snapshot_costs(apps, schema_editor):
    """Fail closed on ambiguous payments; freeze the best available legacy cost.

    The old schema did not retain the purchase cost at sale time.  The only
    deterministic value available is the product purchase price at deployment,
    which is copied once and never recomputed afterwards.
    """
    Payment = apps.get_model('commerce', 'Payment')
    Purchase = apps.get_model('commerce', 'Purchase')
    Sale = apps.get_model('commerce', 'Sale')
    SaleLine = apps.get_model('commerce', 'SaleLine')

    invalid_documents = Payment.objects.filter(
        Q(sale_id__isnull=True, purchase_id__isnull=True)
        | Q(sale_id__isnull=False, purchase_id__isnull=False)
    ).count()
    invalid_amounts = Payment.objects.filter(amount__lte=0).count()
    if invalid_documents or invalid_amounts:
        raise RuntimeError(
            'Migration bloquée : règlements historiques invalides '
            f'(document={invalid_documents}, montant={invalid_amounts}). '
            'Corrigez-les explicitement avant de relancer la migration.'
        )

    overpayments = []
    for row in Payment.objects.filter(sale_id__isnull=False).values('sale_id').annotate(paid=Sum('amount')):
        total = Sale.objects.values_list('total', flat=True).get(pk=row['sale_id'])
        if row['paid'] > total:
            overpayments.append(f"sale:{row['sale_id']}")
    for row in Payment.objects.filter(purchase_id__isnull=False).values('purchase_id').annotate(paid=Sum('amount')):
        total = Purchase.objects.values_list('total', flat=True).get(pk=row['purchase_id'])
        if row['paid'] > total:
            overpayments.append(f"purchase:{row['purchase_id']}")
    if overpayments:
        raise RuntimeError(
            'Migration bloquée : surpaiements historiques détectés sur '
            + ', '.join(overpayments[:20])
        )

    for payment in Payment.objects.filter(reference='').iterator():
        payment.reference = f'PAY-LEGACY-{uuid4().hex[:16].upper()}'
        payment.save(update_fields=['reference'])

    batch = []
    for line in SaleLine.objects.select_related('product').iterator(chunk_size=500):
        line.unit_cost = line.product.purchase_price
        batch.append(line)
        if len(batch) == 500:
            SaleLine.objects.bulk_update(batch, ['unit_cost'])
            batch.clear()
    if batch:
        SaleLine.objects.bulk_update(batch, ['unit_cost'])


def clear_cost_snapshots(apps, schema_editor):
    apps.get_model('commerce', 'SaleLine').objects.update(unit_cost=None)


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_ticketsequence_sale_payment_type_sale_ticket_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_tracking_initialized',
            field=models.BooleanField(default=False, verbose_name='Suivi des règlements initialisé'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_tracking_initialized',
            field=models.BooleanField(default=False, verbose_name='Suivi des règlements initialisé'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True, verbose_name='Coût unitaire historique'),
        ),
        migrations.RunPython(audit_payments_and_snapshot_costs, clear_cost_snapshots),
        migrations.AlterField(
            model_name='purchase',
            name='payment_tracking_initialized',
            field=models.BooleanField(default=True, verbose_name='Suivi des règlements initialisé'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_tracking_initialized',
            field=models.BooleanField(default=True, verbose_name='Suivi des règlements initialisé'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Coût unitaire historique'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commerce.purchase'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Référence paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commerce.sale'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purchase__isnull', True), ('sale__isnull', False)), models.Q(('purchase__isnull', False), ('sale__isnull', True)), _connector='OR'), name='commerce_payment_exactly_one_document'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='commerce_payment_amount_positive'),
        ),
    ]
