# Generated by Django 5.2.17 on 2026-08-16 17:25

import django.db.models.deletion
from django.db import migrations, models


def snapshot_existing_base_units(apps, schema_editor):
    SaleLine = apps.get_model('commerce', 'SaleLine')
    for line in SaleLine.objects.select_related('product__unit').iterator():
        unit = line.product.unit
        line.packaging_name = unit.name if unit else 'Unité'
        line.packaging_factor = 1
        line.packaging_quantity = line.quantity
        line.save(update_fields=('packaging_name', 'packaging_factor', 'packaging_quantity'))


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_reconcile_documents_with_existing_payments'),
        ('inventory', '0012_productpackaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='inventory.productpackaging', verbose_name='Conditionnement'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='packaging_factor',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Facteur historique'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='packaging_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Conditionnement historique'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='packaging_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité vendue'),
        ),
        migrations.RunPython(snapshot_existing_base_units, migrations.RunPython.noop),
    ]
