# Generated by Django 5.2.17 on 2026-09-13 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_sale_created_by'),
        ('inventory', '0015_loadingordersequence_alter_stockmovement_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='loading_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.loadingorder', verbose_name='Chargement opérateur'),
        ),
    ]
