# Generated by Django 5.2.15 on 2026-08-14 16:02

import apps.core.security
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


DEFAULT_CATEGORIES = [
    'Loyer',
    'Électricité',
    'Gaz',
    'Eau',
    'Internet',
    'Téléphone',
    'Salaires',
    'Transport',
    'Carburant',
    'Maintenance',
    'Fournitures',
    'Impôts',
    'Banque',
    'Assurance',
    'Publicité',
    'Divers',
]


def seed_expense_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model('expenses', 'ExpenseCategory')
    for name in DEFAULT_CATEGORIES:
        ExpenseCategory.objects.get_or_create(name=name, defaults={'is_active': True})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0007_alter_product_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de charge',
                'verbose_name_plural': 'Catégories de charges',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Numéro')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('cheque', 'Chèque'), ('transfer', 'Virement'), ('card', 'Carte')], default='cash', max_length=20, verbose_name='Moyen de paiement')),
                ('receipt', models.FileField(blank=True, null=True, upload_to=apps.core.security.expense_receipt_upload_to, validators=[apps.core.security.validate_receipt_upload], verbose_name='Pièce justificative')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='inventory.supplier')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory')),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.RunPython(seed_expense_categories, migrations.RunPython.noop),
    ]
